//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomponenetService.User
{
    public partial class Shop
    {
        protected global::System.Web.UI.WebControls.Repeater rCategories;
        protected global::System.Web.UI.WebControls.RadioButton rbAll;
        protected global::System.Web.UI.WebControls.RadioButton rb0_100;
        protected global::System.Web.UI.WebControls.RadioButton rb100_500;
        protected global::System.Web.UI.WebControls.RadioButton rb500plus;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.LinkButton lbSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        protected global::System.Web.UI.WebControls.Repeater rProducts;
        protected global::System.Web.UI.WebControls.LinkButton lbPrevious;
        protected global::System.Web.UI.WebControls.Repeater rPaging;
        protected global::System.Web.UI.WebControls.LinkButton lbNext;
    }
}
